export {
  adminEnvironmentSchema,
  browserEnvironmentSchema,
  trustedEnvironmentSchema,
  workerEnvironmentSchema,
  type AdminEnvironment,
  type BrowserEnvironment,
  type TrustedEnvironment,
  type WorkerEnvironment,
} from './environment';
export {
  resolveEffectiveTasks,
  type EffectiveTaskCorrection,
  type EffectiveTaskInstance,
  type EffectiveTaskResolution,
  type EffectiveTaskSource,
} from './effective-tasks';
export {
  capturedActionTypeSchema,
  capturedHostnameSchema,
  normalizedBrowserPathSchema,
  observationWindowSchema,
  observationWindowStatusSchema,
  queuedCapturedEventSchema,
  sanitizedCapturedEventSchema,
  semanticInputTokenSchema,
  type CapturedActionType,
  type ObservationWindow,
  type QueuedCapturedEvent,
  type SanitizedCapturedEvent,
} from './observation';
export {
  approvedHostnameSchema,
  departmentNameSchema,
  inviteCodeSchema,
  observerDefaultsSchema,
  privacyPathPrefixSchema,
  roleNameSchema,
  workspaceNameSchema,
  type ObserverDefaultsInput,
} from './study';
export {
  activitySegmentSchema,
  inferredTaskInstanceSchema,
  materializedTaskExclusionSchema,
  normalizationVersion,
  normalizedStepSchema,
  rawEventForNormalizationSchema,
  taskCorrectionInputSchema,
  taskCorrectionTypeSchema,
  taskBoundaryReconciliationSchema,
  taskInferenceOutputSchema,
  taskInferenceExclusionSchema,
  taskExclusionClassificationSchema,
  taskInferencePromptVersion,
  taskInferenceTaskSchema,
  type ActivitySegment,
  type InferredTaskInstance,
  type MaterializedTaskExclusion,
  type NormalizedStep,
  type RawEventForNormalization,
  type TaskCorrectionInput,
  type TaskBoundaryReconciliation,
  type TaskInferenceOutput,
  type TaskInferenceExclusion,
} from './task-inference';
export {
  Constants as databaseConstants,
  type CompositeTypes,
  type Database,
  type Enums,
  type Json,
  type Tables,
  type TablesInsert,
  type TablesUpdate,
} from './database.types';

export const projectIdentity = {
  name: 'Reflow',
  packageScope: '@reflow',
} as const;
